=== DavidS/puppetlabs-catalog_preview/lib/puppet_x/puppetlabs/preview/api/schemas/catalog-delta.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "CatalogDelta",
    "description": "A puppet resource catalog delta",
    "type": "object",
    "properties": {
        "node_name": {
            "type": "string",
            "description": "The name of the node for which the baseline and preview catalogs were compiled"
        },
        "timestamp": {
            "type": "string",
            "description": "When preview run began. In ISO 8601 format with 9 characters second-fragment"
        },
        "produced_by": {
            "type": "string",
            "description": "Name and version of tool that produced this delta"
        },
        "baseline_env": {
            "type": "string",
            "description": "The name of the baseline catalog environment"
        },
        "preview_env": {
            "type": "string",
            "description": "The name of the preview catalog environment"
        },
        "baseline_catalog": {
            "type": "string",
            "description": "the file name of the baseline catalog"
        },
        "preview_catalog": {
            "type": "string",
            "description": "the file name of the preview catalog"
        },
        "baseline_resource_count": {
            "type": "integer",
            "description": "number of resources in the baseline catalog"
        },
        "preview_resource_count": {
            "type": "integer",
            "description": "number of resources in the preview catalog"
        },
        "baseline_edge_count": {
            "type": "integer",
            "description": "number of edges in the baseline catalog"
        },
        "preview_edge_count": {
            "type": "integer",
            "description": "number of edges in the preview catalog"
        },
        "added_resource_count": {
            "type": "integer",
            "description": "number of resources in preview but not in baseline"
        },
        "equal_resource_count": {
            "type": "integer",
            "description": "number of resources in both preview and baseline"
        },
        "missing_resource_count": {
            "type": "integer",
            "description": "number of resources in baseline but not in preview"
        },
        "conflicting_resource_count": {
            "type": "integer",
            "description": "number of resources in both baseline and preview with conflicting attributes"
        },
        "added_edge_count": {
            "type": "integer",
            "description": "number of edges in preview but not in baseline"
        },
        "missing_edge_count": {
            "type": "integer",
            "description": "number of edges in baseline but not in preview"
        },
        "equal_attribute_count": {
            "type": "integer",
            "description": "total number of resource attributes in both preview and baseline"
        },
        "added_attribute_count": {
            "type": "integer",
            "description": "total number of resource attributes in preview but not in baseline"
        },
        "missing_attribute_count": {
            "type": "integer",
            "description": "total number of resource attributes in baseline but not in preview"
        },
        "conflicting_attribute_count": {
            "type": "integer",
            "description": "total number of resource attributes in both baseline and preview with conflicting values"
        },
        "preview_compliant": {
            "type": "boolean",
            "description": "true if the preview catalog has all content in the baseline (may contain more)"
        },
        "preview_equal": {
            "type": "boolean",
            "description": "true if the preview catalog is equal to the baseline catalog"
        },
        "version_equal": {
            "type": "boolean",
            "description": "true if the two catalogs have the same catalog version."
        },
        "missing_resources": {
            "description": "An array of resources in baseline that are not in preview",
            "type": "array",
            "items": {"$ref": "#/definitions/resource"}
        },
        "added_resources": {
            "description": "An array of resources in preview not in baseline",
            "type": "array",
            "items": {"$ref": "#/definitions/resource"}
        },
        "conflicting_resources": {
            "description": "An array of resources in both baseline and preview with conflicting attributes",
            "type": "array",
            "items": {"$ref": "#/definitions/conflicting_resource"}
        },
        "missing_edges": {
            "description": "An array of edges missing in preview",
            "type": "array",
            "items": {"$ref": "#/definitions/edge"}
        },
        "added_edges": {
            "description": "An array of edges in preview that are not in baseline",
            "type": "array",
            "items": {"$ref": "#/definitions/edge"}
        },
        "tags_ignored": {
            "type": "boolean",
            "description": "This delta was produced with tags being ignored"
        },
        "array_value_diff_ignored": {
            "type": "boolean",
            "description": "This delta was produced considering a value equal to a one element array containing that value"
        },
        "string_numeric_diff_ignored": {
            "type": "boolean",
            "description": "This delta was produced considering strings and numbers equal if their numeric representation is the same"
        }
    },
    "required": [
        "node_name",
        "timestamp",
        "produced_by",
        "baseline_env",
        "preview_env",
        "equal_resource_count",
        "added_resource_count",
        "missing_resource_count",
        "conflicting_resource_count",
        "added_edge_count",
        "missing_edge_count",
        "equal_attribute_count",
        "added_attribute_count",
        "missing_attribute_count",
        "conflicting_attribute_count",
        "preview_equal",
        "preview_compliant"
    ],
    "additionalProperties": false,
    "definitions": {
        "location": {
            "type": "object",
            "description": "Describes a location in a file/line",
            "properties": {
                "file": {"type": "string"},
                "line": {"type": "integer"}
            },
            "required": ["file"]
        },
        "attribute": {
            "properties": {
                "diff_id": {"type": "integer"},
                "name": {"type": "string"},
                "value": {}
            },
            "required": ["name", "value"],
            "additionalProperties": false
        },
        "conflicting_attribute": {
            "type": "object",
            "properties": {
                "diff_id": {"type": "integer"},
                "name": {"type": "string"},
                "baseline_value": {},
                "preview_value": {},
                "compliant": {
                    "type": "boolean",
                    "description": "Values different, but preview contains baseline"
                }
            },
            "required": ["name", "baseline_value", "preview_value"],
            "additionalProperties": false
        },
        "resource": {
            "type": "object",
            "properties": {
                "diff_id": {"type": "integer"},
                "location": {
                    "$ref": "#/definitions/location",
                    "description": "The location as reported in the preview"
                },
                "type": {"type": "string"},
                "title": {"type": "string"},
                "attributes": {
                    "type": "array",
                    "items": {"$ref": "#/definitions/attribute"}
                }
            },
            "required": ["type", "title"],
            "additionalProperties": false
        },
        "conflicting_resource": {
            "type": "object",
            "properties": {
                "baseline_location": {
                    "$ref": "#/definitions/location",
                    "description": "The location as reported in the baseline"
                },
                "preview_location": {
                    "$ref": "#/definitions/location",
                    "description": "The location as reported in the preview"
                },
                "diff_id": {"type": "integer"},
                "type": {"type": "string"},
                "title": {"type": "string"},
                "equal_attribute_count": {"type": "integer"},
                "missing_attribute_count": {"type": "integer"},
                "added_attribute_count": {"type": "integer"},
                "conflicting_attribute_count": {"type": "integer"},
                "missing_attributes": {
                    "type": "array",
                    "items": {"$ref": "#/definitions/attribute"}
                },
                "added_attributes": {
                    "type": "array",
                    "items": {"$ref": "#/definitions/attribute"}
                },
                "conflicting_attributes": {
                    "type": "array",
                    "items": {"$ref": "#/definitions/conflicting_attribute"}
                },
                "compliant": {
                    "type": "boolean",
                    "description": "Has attributes that differ, but all are compliant"
                }
            },
            "required": [
                "type",
                "title",
                "equal_attribute_count",
                "missing_attribute_count",
                "added_attribute_count",
                "conflicting_attribute_count"
            ],
            "additionalProperties": false
        },
        "edge": {
            "type": "object",
            "properties": {
                "source": {"type": "string"},
                "target": {"type": "string"},
                "diff_id": {"type": "integer"}
            },
            "required": ["source", "target", "diff_id"],
            "additionalProperties": false
        }
    }
}

=== DavidS/puppetlabs-catalog_preview/spec/fixtures/catalog_deltas/compliant-delta.json
{
    "produced_by": "puppet preview 3.8.0",
    "timestamp": "2015-05-25T18:01:22.753510131+02:00",
    "baseline_catalog": "/path/to/baseline/catalog",
    "preview_catalog": "/path/to/preview/catalog",
    "node_name": "compliant.example.com",
    "tags_ignored": true,
    "string_numeric_diff_ignored": false,
    "baseline_env": "production",
    "preview_env": "preview",
    "version_equal": true,
    "baseline_resource_count": 3,
    "preview_resource_count": 4,
    "added_resources": [
        {
            "location": {
                "file": "/etc/puppet/environments/production/manifests/site.pp",
                "line": 4
            },
            "type": "File",
            "title": "/tmp/baztest",
            "diff_id": 1
        }
    ],
    "added_resource_count": 1,
    "added_attribute_count": 2,
    "missing_resources": [],
    "missing_resource_count": 0,
    "missing_attribute_count": 0,
    "equal_resource_count": 3,
    "equal_attribute_count": 17,
    "conflicting_attribute_count": 0,
    "conflicting_resources": [],
    "conflicting_resource_count": 0,
    "baseline_edge_count": 1,
    "preview_edge_count": 1,
    "added_edges": [],
    "added_edge_count": 0,
    "missing_edges": [],
    "missing_edge_count": 0,
    "preview_compliant": true,
    "preview_equal": false
}

=== DavidS/puppetlabs-catalog_preview/spec/fixtures/catalog_deltas/conflicting-delta.json
{
    "produced_by": "puppet preview 3.8.0",
    "timestamp": "2015-05-21T18:09:01.000869134+02:00",
    "baseline_catalog": "/path/to/baseline/catalog",
    "preview_catalog": "/path/to/preview/catalog",
    "node_name": "different.example.com",
    "tags_ignored": true,
    "string_numeric_diff_ignored": false,
    "baseline_env": "production",
    "preview_env": "preview",
    "version_equal": true,
    "baseline_resource_count": 3,
    "preview_resource_count": 3,
    "added_resources": [
        {
            "location": {
                "file": "/etc/puppet/environments/production/manifests/site.pp",
                "line": 4
            },
            "type": "File",
            "title": "/tmp/baztest",
            "diff_id": 1
        }
    ],
    "added_resource_count": 1,
    "added_attribute_count": 3,
    "missing_resources": [
        {
            "location": {
                "file": "/etc/puppet/environments/production/manifests/site.pp",
                "line": 3
            },
            "type": "File",
            "title": "/tmp/fumtest",
            "diff_id": 2
        }
    ],
    "missing_resource_count": 1,
    "missing_attribute_count": 11,
    "equal_resource_count": 1,
    "equal_attribute_count": 12,
    "conflicting_attribute_count": 1,
    "conflicting_resources": [
        {
            "baseline_location": {
                "file": "/etc/puppet/environments/production/manifests/site.pp",
                "line": 2
            },
            "preview_location": {
                "file": "/etc/puppet/environments/production/manifests/site.pp",
                "line": 2
            },
            "type": "File",
            "title": "/tmp/bartest",
            "equal_attribute_count": 9,
            "added_attributes": [
                {
                    "name": "added",
                    "value": "Just arrived",
                    "diff_id": 4
                }
            ],
            "added_attribute_count": 1,
            "missing_attributes": [
                {
                    "name": "array",
                    "value": [
                        "a",
                        "b",
                        "c",
                        "c"
                    ],
                    "diff_id": 5
                },
                {
                    "name": "before",
                    "value": "#<Set:0x00000003b20220>",
                    "diff_id": 6
                },
                {
                    "name": "after",
                    "value": "#<Set:0x00000003b1be00>",
                    "diff_id": 7
                },
                {
                    "name": "subscribe",
                    "value": "#<Set:0x00000003b1bb80>",
                    "diff_id": 8
                },
                {
                    "name": "notify",
                    "value": "#<Set:0x00000003b1b9f0>",
                    "diff_id": 9
                },
                {
                    "name": "hash",
                    "value": {
                        "a": "A",
                        "b": [
                            1,
                            2
                        ]
                    },
                    "diff_id": 10
                },
                {
                    "name": "mol",
                    "value": "42",
                    "diff_id": 11
                }
            ],
            "missing_attribute_count": 7,
            "conflicting_attributes": [
                {
                    "name": "ensure",
                    "baseline_value": "present",
                    "preview_value": "purged",
                    "compliant": false,
                    "diff_id": 12
                }
            ],
            "conflicting_attribute_count": 1,
            "diff_id": 3
        }
    ],
    "conflicting_resource_count": 1,
    "baseline_edge_count": 1,
    "preview_edge_count": 1,
    "added_edges": [
        {
            "source": "Class[main]",
            "target": "File[/tmp/bartest]",
            "diff_id": 13
        }
    ],
    "added_edge_count": 1,
    "missing_edges": [
        {
            "source": "Class[main]",
            "target": "File[/tmp/footest]",
            "diff_id": 14
        }
    ],
    "missing_edge_count": 1,
    "preview_compliant": false,
    "preview_equal": false
}

=== DavidS/puppetlabs-catalog_preview/spec/fixtures/catalog_deltas/conflict-without-location-delta.json
{
  "produced_by": "puppet preview 3.8.0",
  "timestamp": "2015-06-11T13:08:41.289367239+02:00",
  "baseline_catalog": "/home/bob/.puppet/var/preview/test.example.com/baseline_catalog.json",
  "preview_catalog": "/home/bob/.puppet/var/preview/test.example.com/preview_catalog.json",
  "node_name": "test.example.com",
  "baseline_env": "production",
  "preview_env": "preview",
  "version_equal": true,
  "baseline_resource_count": 5,
  "preview_resource_count": 7,
  "added_resources": [
    {
      "location": {
        "file": "/etc/puppet/environments/preview/manifests/site.pp",
        "line": 6
      },
      "type": "Stage",
      "title": "first",
      "diff_id": 1
    },
    {
      "location": {
        "file": "/etc/puppet/environments/preview/manifests/site.pp",
        "line": 9
      },
      "type": "Stage",
      "title": "last",
      "diff_id": 2
    }
  ],
  "added_resource_count": 2,
  "added_attribute_count": 6,
  "missing_resources": [

  ],
  "missing_resource_count": 0,
  "missing_attribute_count": 0,
  "equal_resource_count": 3,
  "equal_attribute_count": 12,
  "conflicting_attribute_count": 1,
  "conflicting_resources": [
    {
      "type": "Stage",
      "title": "main",
      "equal_attribute_count": 3,
      "added_attributes": [
        {
          "name": "before",
          "value": "#<Set:0x0000000556a888>",
          "diff_id": 4
        }
      ],
      "added_attribute_count": 1,
      "missing_attributes": [

      ],
      "missing_attribute_count": 0,
      "conflicting_attributes": [

      ],
      "conflicting_attribute_count": 0,
      "diff_id": 3
    },
    {
      "baseline_location": {
        "file": "/etc/puppet/environments/production/manifests/site.pp",
        "line": 4
      },
      "preview_location": {
        "file": "/etc/puppet/environments/preview/manifests/site.pp",
        "line": 2
      },
      "type": "Notify",
      "title": "preview compile diff test",
      "equal_attribute_count": 2,
      "added_attributes": [

      ],
      "added_attribute_count": 0,
      "missing_attributes": [

      ],
      "missing_attribute_count": 0,
      "conflicting_attributes": [
        {
          "name": "message",
          "baseline_value": "42",
          "preview_value": 42,
          "diff_id": 6
        }
      ],
      "conflicting_attribute_count": 1,
      "diff_id": 5
    }
  ],
  "conflicting_resource_count": 2,
  "baseline_edge_count": 4,
  "preview_edge_count": 4,
  "added_edges": [

  ],
  "added_edge_count": 0,
  "missing_edges": [

  ],
  "missing_edge_count": 0,
  "preview_compliant": false,
  "preview_equal": false
}

=== DavidS/puppetlabs-catalog_preview/spec/fixtures/catalog_deltas/equal-delta.json
{
    "produced_by": "puppet preview 3.8.0",
    "timestamp": "2015-05-25T18:10:27.123815346+02:00",
    "baseline_catalog": "/path/to/baseline/catalog",
    "preview_catalog": "/path/to/preview/catalog",
    "node_name": "ok.example.com",
    "tags_ignored": true,
    "string_numeric_diff_ignored": false,
    "baseline_env": "production",
    "preview_env": "preview",
    "version_equal": true,
    "baseline_resource_count": 3,
    "preview_resource_count": 3,
    "added_resources": [],
    "added_resource_count": 0,
    "added_attribute_count": 0,
    "missing_resources": [],
    "missing_resource_count": 0,
    "missing_attribute_count": 0,
    "equal_resource_count": 3,
    "equal_attribute_count": 17,
    "conflicting_attribute_count": 0,
    "conflicting_resources": [],
    "conflicting_resource_count": 0,
    "baseline_edge_count": 1,
    "preview_edge_count": 1,
    "added_edges": [],
    "added_edge_count": 0,
    "missing_edges": [],
    "missing_edge_count": 0,
    "preview_compliant": true,
    "preview_equal": true
}
